//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloServiceClient.HelloService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HelloService.HelloServiceSoap")]
    public interface HelloServiceSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGreetingsMessage", ReplyAction="*")]
        HelloServiceClient.HelloService.GetGreetingsMessageResponse GetGreetingsMessage(HelloServiceClient.HelloService.GetGreetingsMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGreetingsMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<HelloServiceClient.HelloService.GetGreetingsMessageResponse> GetGreetingsMessageAsync(HelloServiceClient.HelloService.GetGreetingsMessageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGreetingsMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGreetingsMessage", Namespace="http://tempuri.org/", Order=0)]
        public HelloServiceClient.HelloService.GetGreetingsMessageRequestBody Body;
        
        public GetGreetingsMessageRequest() {
        }
        
        public GetGreetingsMessageRequest(HelloServiceClient.HelloService.GetGreetingsMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGreetingsMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public GetGreetingsMessageRequestBody() {
        }
        
        public GetGreetingsMessageRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGreetingsMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGreetingsMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public HelloServiceClient.HelloService.GetGreetingsMessageResponseBody Body;
        
        public GetGreetingsMessageResponse() {
        }
        
        public GetGreetingsMessageResponse(HelloServiceClient.HelloService.GetGreetingsMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGreetingsMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetGreetingsMessageResult;
        
        public GetGreetingsMessageResponseBody() {
        }
        
        public GetGreetingsMessageResponseBody(string GetGreetingsMessageResult) {
            this.GetGreetingsMessageResult = GetGreetingsMessageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HelloServiceSoapChannel : HelloServiceClient.HelloService.HelloServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloServiceSoapClient : System.ServiceModel.ClientBase<HelloServiceClient.HelloService.HelloServiceSoap>, HelloServiceClient.HelloService.HelloServiceSoap {
        
        public HelloServiceSoapClient() {
        }
        
        public HelloServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelloServiceClient.HelloService.GetGreetingsMessageResponse HelloServiceClient.HelloService.HelloServiceSoap.GetGreetingsMessage(HelloServiceClient.HelloService.GetGreetingsMessageRequest request) {
            return base.Channel.GetGreetingsMessage(request);
        }
        
        public string GetGreetingsMessage(string name) {
            HelloServiceClient.HelloService.GetGreetingsMessageRequest inValue = new HelloServiceClient.HelloService.GetGreetingsMessageRequest();
            inValue.Body = new HelloServiceClient.HelloService.GetGreetingsMessageRequestBody();
            inValue.Body.name = name;
            HelloServiceClient.HelloService.GetGreetingsMessageResponse retVal = ((HelloServiceClient.HelloService.HelloServiceSoap)(this)).GetGreetingsMessage(inValue);
            return retVal.Body.GetGreetingsMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HelloServiceClient.HelloService.GetGreetingsMessageResponse> HelloServiceClient.HelloService.HelloServiceSoap.GetGreetingsMessageAsync(HelloServiceClient.HelloService.GetGreetingsMessageRequest request) {
            return base.Channel.GetGreetingsMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<HelloServiceClient.HelloService.GetGreetingsMessageResponse> GetGreetingsMessageAsync(string name) {
            HelloServiceClient.HelloService.GetGreetingsMessageRequest inValue = new HelloServiceClient.HelloService.GetGreetingsMessageRequest();
            inValue.Body = new HelloServiceClient.HelloService.GetGreetingsMessageRequestBody();
            inValue.Body.name = name;
            return ((HelloServiceClient.HelloService.HelloServiceSoap)(this)).GetGreetingsMessageAsync(inValue);
        }
    }
}
